import type { NextPage } from 'next';
import Head from 'next/head';
import { Header, Footer, ContentsContainer } from '../components/common';
import SelectBox from '../components/common/SelectBox';

const SamplePage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <ContentsContainer>
                <SelectBox>
                    <option value="test">asdsad</option>
                    <option value="test">asdsad</option>
                    <option value="test">asdsad</option>
                    <option value="test">asdsad</option>
                    <option value="test">asdsad</option>
                </SelectBox>
            </ContentsContainer>
            <Footer />
        </div>
    );
};

export default SamplePage;
