import type { NextPage } from 'next';
import Head from 'next/head';
import { Header, Footer, ContentsContainer } from '../../components/common';
import SurveyContainer from '../../components/survey/SurveyContainer';

const SurveyPage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <ContentsContainer>
                <SurveyContainer />
            </ContentsContainer>
            <Footer />
        </div>
    );
};

export default SurveyPage;
